import React, { Component } from 'react';
import Container from '../Container/Container';
import './TheSolution.css';

class TheSolution extends Component {
  render() {
    return (
      <div className="TheSolution">
        <Container>
          <p>
            Clarify is a short 10 day program of empowering, expanding,
            and "clarifying" exercises, all thematically linked and designed
            to help you create a pattern of meaningful next-steps in your life.
          </p>
          <p>
            Built upon the premise that meaning is generated by making a
            connection between two points, Clarify focuses in on the two
            points of <span>where you are</span> and <span>where you're headed</span>.
            However, meaning generated from any connection can either be
            empowering or limiting.  And, to know where you are truly, it is
            essential to have a sense of <span>where you have come from</span>.
          </p>
          <p>
            Therefore, Clarify is built with a past->future-> present model, beginning with creating empowering meaning from your past, followed by clarifying a vision of your future, and finishing with introducing tools that begin building momentum in your present.
          </p>
        </Container>
      </div>
    );
  }
}

export default TheSolution;
